from __future__ import annotations

from app.models.schemas import EvPreset, EvType

EV_PRESETS: list[EvPreset] = [
  EvPreset(
    id="tesla-model-3-lr",
    name="Tesla Model 3 Long Range",
    vendor="Tesla",
    model="Model 3 LR",
    ev_type=EvType.BEV,
    battery_capacity_kwh=82.0,
    max_ac_charge_power_kw=11.5,
    max_dc_charge_power_kw=250.0,
  ),
  EvPreset(
    id="nissan-leaf-plus",
    name="Nissan Leaf e+",
    vendor="Nissan",
    model="Leaf e+",
    ev_type=EvType.BEV,
    battery_capacity_kwh=62.0,
    max_ac_charge_power_kw=6.6,
    max_dc_charge_power_kw=100.0,
  ),
  EvPreset(
    id="bmw-i4",
    name="BMW i4 eDrive40",
    vendor="BMW",
    model="i4 eDrive40",
    ev_type=EvType.BEV,
    battery_capacity_kwh=83.9,
    max_ac_charge_power_kw=11.0,
    max_dc_charge_power_kw=205.0,
  ),
  EvPreset(
    id="hyundai-ioniq5",
    name="Hyundai IONIQ 5",
    vendor="Hyundai",
    model="IONIQ 5",
    ev_type=EvType.BEV,
    battery_capacity_kwh=77.4,
    max_ac_charge_power_kw=11.0,
    max_dc_charge_power_kw=233.0,
  ),
  EvPreset(
    id="chevy-bolt",
    name="Chevrolet Bolt EV",
    vendor="Chevrolet",
    model="Bolt EV",
    ev_type=EvType.BEV,
    battery_capacity_kwh=65.0,
    max_ac_charge_power_kw=7.7,
    max_dc_charge_power_kw=55.0,
  ),
  EvPreset(
    id="vw-id4",
    name="Volkswagen ID.4",
    vendor="Volkswagen",
    model="ID.4 Pro",
    ev_type=EvType.BEV,
    battery_capacity_kwh=82.0,
    max_ac_charge_power_kw=11.0,
    max_dc_charge_power_kw=135.0,
  ),
  EvPreset(
    id="toyota-prius-prime",
    name="Toyota Prius Prime",
    vendor="Toyota",
    model="Prius Prime",
    ev_type=EvType.PHEV,
    battery_capacity_kwh=13.6,
    max_ac_charge_power_kw=3.3,
    max_dc_charge_power_kw=0.0,
  ),
  EvPreset(
    id="generic-bev",
    name="Generic BEV",
    vendor="Generic",
    model="Standard BEV",
    ev_type=EvType.BEV,
    battery_capacity_kwh=75.0,
    max_ac_charge_power_kw=11.0,
    max_dc_charge_power_kw=150.0,
  ),
]
